package vision

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"testing"
)

// gemma4Golden mirrors scripts/pin_gemma4_vision.py's JSON output (goinfer repo).
type gemma4Golden struct {
	Config struct {
		HiddenSize        int     `json:"hidden_size"`
		IntermediateSize  int     `json:"intermediate_size"`
		NumHiddenLayers   int     `json:"num_hidden_layers"`
		NumAttentionHeads int     `json:"num_attention_heads"`
		HeadDim           int     `json:"head_dim"`
		PatchSize         int     `json:"patch_size"`
		PoolingKernelSize int     `json:"pooling_kernel_size"`
		PosEmbTableSize   int     `json:"position_embedding_size"`
		RMSNormEps        float64 `json:"rms_norm_eps"`
		UseClippedLinears bool    `json:"use_clipped_linears"`
	} `json:"config"`
	TextHiddenSize   int       `json:"text_hidden_size"`
	NumPatches       int       `json:"num_patches"`
	PatchesShape     []int     `json:"patches_shape"`
	Patches          []float32 `json:"patches"`
	PositionIDsShape []int     `json:"position_ids_shape"`
	PositionIDs      []int     `json:"position_ids"`
	PooledShape      []int     `json:"pooled_shape"`
	Pooled           []float32 `json:"pooled"`
	ProjectedShape   []int     `json:"projected_shape"`
	Projected        []float32 `json:"projected"`
}

// gemma4Testdata resolves aikit's own testdata/ directory (module root, one
// level up from vision/) — same convention as siglip-tiny/qwen25vl-vision-tiny.
// Generated by goinfer's scripts/pin_gemma4_vision.py, then copied here.
func gemma4Testdata(t *testing.T, name string) string {
	t.Helper()
	p := filepath.Join("..", "testdata", name)
	if _, err := os.Stat(p); err != nil {
		t.Skipf("testdata fixture %s not found at %s (regenerate via goinfer's scripts/pin_gemma4_vision.py): %v", name, p, err)
	}
	return p
}

func cosineSim(a, b []float32) float64 {
	if len(a) != len(b) {
		return math.NaN()
	}
	var dot, na, nb float64
	for i := range a {
		dot += float64(a[i]) * float64(b[i])
		na += float64(a[i]) * float64(a[i])
		nb += float64(b[i]) * float64(b[i])
	}
	if na == 0 || nb == 0 {
		return math.NaN()
	}
	return dot / (math.Sqrt(na) * math.Sqrt(nb))
}

// TestGemma4Encoder_tinyGoldenParity loads the tiny-random Gemma4VisionModel +
// Gemma4MultimodalEmbedder checkpoint (scripts/pin_gemma4_vision.py) and checks
// Gemma4Encoder.Forward reproduces the real HF forward's projected soft-token
// output at cosine ~= 1.0. Exercises every real component: sandwich RMSNorm,
// gated tanh-GELU MLP, per-head q/k/v RMSNorm (v unscaled), axial 2-D rope,
// hardcoded attention scale 1.0, the REAL (non-default, non-inf) ClippableLinear
// clamp, 3x3 average pooling, and the unscaled-RMSNorm+Linear projector.
func TestGemma4Encoder_tinyGoldenParity(t *testing.T) {
	goldenPath := gemma4Testdata(t, "gemma4_vision_golden.json")
	ckptDir := gemma4Testdata(t, "gemma4-vision-tiny")

	raw, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var g gemma4Golden
	if err := json.Unmarshal(raw, &g); err != nil {
		t.Fatalf("parse golden: %v", err)
	}

	enc, err := LoadGemma4Encoder(ckptDir, false)
	if err != nil {
		t.Fatalf("LoadGemma4Encoder: %v", err)
	}
	if enc.Cfg.HiddenSize != g.Config.HiddenSize || enc.Cfg.NumHiddenLayers != g.Config.NumHiddenLayers {
		t.Fatalf("loaded config mismatch: got hidden=%d layers=%d, want hidden=%d layers=%d",
			enc.Cfg.HiddenSize, enc.Cfg.NumHiddenLayers, g.Config.HiddenSize, g.Config.NumHiddenLayers)
	}
	if enc.TextHiddenSize != g.TextHiddenSize {
		t.Fatalf("TextHiddenSize = %d, want %d", enc.TextHiddenSize, g.TextHiddenSize)
	}

	if len(g.PositionIDsShape) != 3 || g.PositionIDsShape[1] != g.NumPatches || g.PositionIDsShape[2] != 2 {
		t.Fatalf("unexpected position_ids_shape %v", g.PositionIDsShape)
	}
	positionIDs := make([][2]int, g.NumPatches)
	for i := range positionIDs {
		positionIDs[i] = [2]int{g.PositionIDs[i*2], g.PositionIDs[i*2+1]}
	}

	got, err := enc.Forward(g.Patches, positionIDs)
	if err != nil {
		t.Fatalf("Forward: %v", err)
	}
	if len(got) != len(g.Projected) {
		t.Fatalf("output len %d, want %d (shape %v)", len(got), len(g.Projected), g.ProjectedShape)
	}
	cos := cosineSim(got, g.Projected)
	if cos < 0.999999 {
		var maxDiff float32
		for i := range got {
			d := got[i] - g.Projected[i]
			if d < 0 {
				d = -d
			}
			if d > maxDiff {
				maxDiff = d
			}
		}
		n := min(8, len(got))
		t.Fatalf("cosine = %.9f (want >= 0.999999), max|diff| = %g\ngot[:8]  = %v\nwant[:8] = %v", cos, maxDiff, got[:n], g.Projected[:n])
	}
	t.Logf("gemma4 vision tiny-golden parity: cosine = %.9f, %d pooled tokens", cos, len(got)/enc.TextHiddenSize)
}
