//go:build linux

// Package anncuda registers a native-CUDA implementation of ann.Backend, so an
// ann.FlatI8 that calls EnableGPU scores its int8 corpus GEMV on the GPU. It is
// the Linux mirror of gpu/annmetal (docs/task-native-gpu.md, Phase 1b) — same
// seam, same two kernels, same parity gate — built on the CUDA half of aikit's
// device substrate (gpu/cuda.go).
//
// Importing this package is the opt-in: aikit's core `ann` never imports `gpu`,
// so the default build stays pure-Go CPU.
//
// The kernels live in gemv_w8a8.cu and ship as embedded PTX: gemv_w8a8 scores ONE
// query against the whole index (FlatI8.Query), gemv_w8a8_batch8/16 score M queries
// in one launch (FlatI8.QueryBatch, FlatI8.TopKBatch), and topk_rows selects on the
// device. All compute the exact int32 dot of the host-quantized int8 query against
// each row, then the query/row rescale — the same value the CPU linalg.MatmulBTW8A8
// produces, so GPU and CPU rank identically.
package anncuda

import (
	_ "embed"
	"fmt"
	"math"
	"sync"
	"unsafe"

	"github.com/townsendmerino/aikit/ann"
	gpu "github.com/townsendmerino/aikit/gpu"
)

// w8a8PTX is the build artifact of gemv_w8a8.cu, regenerated by ../build_ptx.sh.
// Embedding PTX (rather than compiling CUDA C at run time, the way the Metal side
// compiles MSL) is what keeps the runtime toolkit-free: only libcuda is needed,
// and the driver JITs this.
//
//go:embed testdata/gemv_w8a8.ptx
var w8a8PTX []byte

type cudaBackend struct {
	dev  *gpu.Device
	q    gpu.Queue
	gemv gpu.Pipeline // one query  × N rows (FlatI8.Query)
	// The two batch instantiations differ only in their (LANES, QTILE) constants,
	// which gemv_w8a8.cu records the sweep for. batchSmall is 8 lanes/row × 8
	// queries/tile, batchWide 4 × 16; batchQTile below is the selection rule.
	batchSmall gpu.Pipeline // M ≤ batchSmallMaxM
	batchWide  gpu.Pipeline // M >  batchSmallMaxM
	// The register top-k kernels, INDEXED BY topkWidths — same order, same length.
	// Keeping them in an array rather than four named fields is what lets the routing
	// be a lookup instead of a hand-written switch, so there is no second place for the
	// k -> kernel mapping to be wrong. topk is the k-pass fallback above the widest.
	topkReg [len(topkWidths)]gpu.Pipeline
	// The split/merge pair, same widths and same order. Used when one block per query
	// would leave the device idle — see topkSplitParts.
	topkSplit [len(topkWidths)]gpu.Pipeline
	topkMerge [len(topkWidths)]gpu.Pipeline
	sm        int // multiprocessor count, 0 if the driver would not say
	topk      gpu.Pipeline
}

// init reaches CUDA and registers the backend. If there is no CUDA device (no
// libcuda, no GPU) or the PTX fails to load, it registers nothing — ann.FlatI8
// then stays on the CPU and EnableGPU returns "no backend".
func init() {
	dev, err := gpu.CreateSystemDefaultDevice()
	if err != nil {
		return
	}
	lib, err := dev.CompileLibrary(w8a8PTX)
	if err != nil {
		dev.ReleaseObjects()
		return
	}
	gemv, err := dev.NewComputePipeline(lib, "gemv_w8a8")
	if err != nil {
		dev.ReleaseObjects()
		return
	}
	batchSmall, err := dev.NewComputePipeline(lib, "gemv_w8a8_batch8")
	if err != nil {
		dev.ReleaseObjects()
		return
	}
	batchWide, err := dev.NewComputePipeline(lib, "gemv_w8a8_batch16")
	if err != nil {
		dev.ReleaseObjects()
		return
	}
	topk, err := dev.NewComputePipeline(lib, "topk_rows")
	if err != nil {
		dev.ReleaseObjects()
		return
	}
	var topkReg, topkSplit, topkMerge [len(topkWidths)]gpu.Pipeline
	for i, w := range topkWidths {
		for _, load := range []struct {
			name string
			dst  *gpu.Pipeline
		}{
			{topkKernelName("rows", w), &topkReg[i]},
			{topkKernelName("split", w), &topkSplit[i]},
			{topkKernelName("merge", w), &topkMerge[i]},
		} {
			p, err := dev.NewComputePipeline(lib, load.name)
			if err != nil {
				dev.ReleaseObjects()
				return
			}
			*load.dst = p
		}
	}
	ann.RegisterBackend(&cudaBackend{
		dev: dev, q: dev.NewCommandQueue(),
		gemv: gemv, batchSmall: batchSmall, batchWide: batchWide,
		topk: topk, topkReg: topkReg, topkSplit: topkSplit, topkMerge: topkMerge,
		sm: dev.SMCount(),
	})
}

func (b *cudaBackend) Name() string { return "cuda" }

// NewI8Index uploads the int8 codes + scales resident on the device and allocates
// the reusable per-query scratch (quantized query, query scale, output, and the
// row count the kernels bounds-check against).
func (b *cudaBackend) NewI8Index(bq []int8, scales []float32, n, dim int) (idx ann.I8Index, err error) {
	if n <= 0 || dim <= 0 {
		return nil, fmt.Errorf("gpu: empty int8 index (n=%d dim=%d)", n, dim)
	}
	if len(bq) != n*dim || len(scales) != n {
		return nil, fmt.Errorf("gpu: int8 index shape mismatch (bq %d, scales %d, n=%d dim=%d)", len(bq), len(scales), n, dim)
	}
	// A corpus upload is the one allocation here big enough to exhaust device
	// memory, and the device layer reports OOM as a loud panic (MustBuf) rather
	// than a silently unusable buffer. Recover it into an error so EnableGPU
	// declines and the index keeps scoring on the CPU — the right answer for OOM.
	//
	// Buffers are declared BEFORE the defer and assigned by name rather than
	// inline in the returned struct, so a panic part-way through this sequence
	// is released rather than leaked (audit C-04, ported from gpu/annmetal,
	// which got this fix first — this constructor used to register its recover
	// before any allocation but had nothing by which to release the ones that
	// had already landed, so e.g. codes/scales/qi8 succeeding and qscale then
	// hitting OOM leaked all three, on the one path where device memory is by
	// definition short). ReleaseBuf ignores the zero Buffer, so the loop below
	// is safe over fields a panic never reached.
	var codes, scl, qi8, qscale, kbuf, nbuf, out gpu.Buffer
	defer func() {
		if r := recover(); r != nil {
			for _, buf := range []gpu.Buffer{codes, scl, qi8, qscale, kbuf, nbuf, out} {
				b.dev.ReleaseBuf(buf)
			}
			idx, err = nil, fmt.Errorf("gpu: device upload failed: %v", r)
		}
	}()
	codes = gpu.NewBufferOf(b.dev, bq)
	scl = gpu.NewBufferOf(b.dev, scales)
	qi8 = gpu.NewBufferOf(b.dev, make([]int8, dim))
	qscale = gpu.NewBufferOf(b.dev, []float32{0})
	kbuf = gpu.NewBufferOf(b.dev, []uint32{uint32(dim)})
	nbuf = gpu.NewBufferOf(b.dev, []uint32{uint32(n)})
	out = b.dev.NewBufferLen(n)
	return &cudaI8Index{
		b: b, n: n, dim: dim,
		codes: codes, scales: scl, qi8: qi8, qscale: qscale, kbuf: kbuf, nbuf: nbuf, out: out,
		hq: make([]int8, dim),
	}, nil
}

type cudaI8Index struct {
	b      *cudaBackend
	n, dim int
	codes  gpu.Buffer // [n*dim] int8 (resident)
	scales gpu.Buffer // [n] f32
	qi8    gpu.Buffer // [dim] int8 (reused per query)
	qscale gpu.Buffer // [1] f32 (reused)
	kbuf   gpu.Buffer // [1] u32 — dim
	nbuf   gpu.Buffer // [1] u32 — row count, the kernel's launch bound
	out    gpu.Buffer // [n] f32 (reused)
	hq     []int8     // host staging for the quantized query (reused)
	mu     sync.Mutex
	// tk is the reused device scratch for SMALL top-k batches. Large batches keep
	// allocating per call — see topkScratchMaxM.
	tk topkScratch
}

// Score dynamically quantizes q on the host (byte-identical to linalg's
// quantizeRowInt8), uploads it, dispatches the GEMV, and copies the scores back.
// Serialized: the reused scratch buffers are per-index, and one stream runs
// serially.
//
// Where the Metal path writes the quantized query straight into the buffer's UMA
// mapping, CUDA memory is not host-visible — hence the host staging slice plus an
// explicit upload (gpu/cuda.go, divergence 1).
func (x *cudaI8Index) Score(q []float32, dst []float32) error {
	if len(q) != x.dim {
		return fmt.Errorf("gpu: query dim %d != index dim %d", len(q), x.dim)
	}
	if len(dst) != x.n {
		return fmt.Errorf("gpu: dst len %d != index n %d", len(dst), x.n)
	}
	x.mu.Lock()
	defer x.mu.Unlock()
	qscale := quantizeRowInt8(q, x.hq)
	if err := gpu.Upload(x.qi8, x.hq); err != nil {
		return err
	}
	if err := gpu.Upload(x.qscale, []float32{qscale}); err != nil {
		return err
	}
	// gemv_w8a8 puts a LANE GROUP on each row, not a thread: gemvLanes threads
	// cooperate on one row so their loads coalesce. The dispatch is therefore
	// n*gemvLanes threads, and the kernel's own bound check compares the global
	// lane-group index against n.
	if err := x.b.q.Run1D(x.b.gemv, x.n*gemvLanes, batchBlock, x.codes, x.qi8, x.scales, x.kbuf, x.qscale, x.out, x.nbuf); err != nil {
		return err
	}
	return gpu.Download(x.out, dst)
}

// ScoreBatch scores M = len(queries) queries against all N rows in a single
// dispatch of the batched GEMM — the throughput win over calling Score in a loop.
// dst is [M*N] row-major (dst[m*N+j]). Per-call scratch is allocated and released
// each call: batch queries are the infrequent path, so this stays simple rather
// than caching an M-sized arena.
func (x *cudaI8Index) ScoreBatch(queries [][]float32, dst []float32) (err error) {
	M := len(queries)
	if M == 0 {
		return nil
	}
	N, K := x.n, x.dim
	if len(dst) != M*N {
		return fmt.Errorf("gpu: batch dst len %d != M*N %d", len(dst), M*N)
	}
	qi8 := make([]int8, M*K)
	qscale := make([]float32, M)
	for m, q := range queries {
		if len(q) != K {
			return fmt.Errorf("gpu: batch query %d dim %d != index dim %d", m, len(q), K)
		}
		qscale[m] = quantizeRowInt8(q, qi8[m*K:(m+1)*K])
	}
	x.mu.Lock()
	defer x.mu.Unlock()
	// Same OOM-to-error contract as NewI8Index (audit C-04): an M×N output can
	// be large. Declared before the defer, one defer instead of two, so a
	// partial allocation is released rather than leaked — the release used to
	// be its own defer registered AFTER the three allocations, so a panic on
	// the second or third left the first one leaked for the life of the
	// process (nothing else references it).
	var qi8Buf, qscaleBuf, outBuf gpu.Buffer
	defer func() {
		for _, b := range []gpu.Buffer{qi8Buf, qscaleBuf, outBuf} {
			x.b.dev.ReleaseBuf(b)
		}
		if r := recover(); r != nil {
			err = fmt.Errorf("gpu: batch scratch allocation failed: %v", r)
		}
	}()
	qi8Buf = gpu.NewBufferOf(x.b.dev, qi8)
	qscaleBuf = gpu.NewBufferOf(x.b.dev, qscale)
	outBuf = x.b.dev.NewBufferLen(M * N)
	if err := x.launchBatch(qi8Buf, qscaleBuf, outBuf, M, N, K); err != nil {
		return err
	}
	if err := x.b.q.Sync(); err != nil {
		return err
	}
	return gpu.Download(outBuf, dst)
}

// Close releases this index's device buffers (the shared device stays alive for
// other indexes; the process holds one CUDA context).
func (x *cudaI8Index) Close() error {
	t := &x.tk
	for _, b := range []gpu.Buffer{x.codes, x.scales, x.qi8, x.qscale, x.kbuf, x.nbuf, x.out,
		t.qi8, t.qscale, t.score, t.idx, t.val, t.pIdx, t.pVal, t.mBuf, t.kBuf, t.pBuf} {
		x.b.dev.ReleaseBuf(b)
	}
	return nil
}

// quantizeRowInt8 replicates linalg's (unexported) per-row int8 quantizer exactly:
// scale = maxAbs/127, dst[k] = round(q[k]/scale) clamped to ±127; all-zero input →
// scale 0. Kept byte-identical so the GPU int8 dot equals the CPU one. (Identical
// to gpu/annmetal's copy — same reference, and the two backends never build
// together.)
func quantizeRowInt8(a []float32, dst []int8) (scale float32) {
	var maxAbs float32
	for _, v := range a {
		if v < 0 {
			v = -v
		}
		if v > maxAbs {
			maxAbs = v
		}
	}
	if maxAbs == 0 {
		for k := range dst {
			dst[k] = 0
		}
		return 0
	}
	scale = maxAbs / 127
	inv := 1.0 / scale
	for k, v := range a {
		x := math.Round(float64(v * inv))
		if x > 127 {
			x = 127
		} else if x < -127 {
			x = -127
		}
		dst[k] = int8(x)
	}
	return scale
}

// topkMinN is the row count below which TopKBatch declines to the score-then-host-topk
// path. It is DERIVED FROM THIS BOX's sweep, not copied from Metal: the second launch
// has to earn back more than the readback it saves, and CUDA's launch floor (~µs) sits
// two orders of magnitude below Metal's command-buffer floor (~250 µs), so the two
// platforms cross over in different places. See docs/BENCH-gpu-results.md.
const topkMinN = 50_000

// topkMinBatch does not exist any more. It WAS 8, gating TopKBatch to decline
// batches smaller than that — about occupancy: topk_rows ran ONE BLOCK PER
// QUERY, so a batch of 1 occupied a single SM of 40 while the rest idled.
// Measured then: at N=100k, batch=1 went 0.79x -> 0.43x with device top-k
// unconditionally on, while batch=8 went 0.88x -> 3.93x. So the kernel
// needed a real batch behind it.
//
// It does not any more. topkSplitParts splits one query's row across as many
// blocks as the device has room for, which is precisely the case this
// constant used to exclude. Re-measured at N=200k k=10, device top-k against
// ScoreBatch + host selection (the fallback TopKBatch hands work to):
//
//	M=1   1.02 ms vs 1.20   1.18x      M=16   2.05 vs  5.55   2.71x
//	M=2   1.18 vs 1.54      1.31x      M=64   6.47 vs 29.94   4.63x
//	M=8   1.44 vs 3.15      2.18x      M=256 24.56 vs 79.20   3.22x
//
// Device selection wins at every width, so the batch-size gate in TopKBatch is
// deleted rather than set to 1 — TopKBatch already returns early on M==0, so a
// "M < 1" check would have been permanently dead code, not a decision anyone
// could still tune. A constant that encodes a kernel's limitation has to be
// re-derived when the limitation is removed — this file has now produced
// three of those (gemmTileMinM, this one, and gemv's warp width), an
// argument for deriving such things from a measurement rather than storing
// them.

// batchSmallMaxM is where the wider query tile starts to pay, and both halves of the
// choice were swept rather than reasoned (the table is in gemv_w8a8.cu). The narrow
// kernel tiles 8 queries and the wide one 16, so a batch of M pays for ceil(M/QTILE)
// full tiles: at M=8 the wide kernel computes 16 accumulators to store 8, which costs
// more than the extra corpus pass the narrow kernel makes. Above 8 that reverses,
// because a second pass over an N×K corpus is far more expensive than padded MACs.
//
// This replaced gemmTileMinM = 2, which selected gpu/vit.cu's 16×16 tiled GEMM. That
// constant was measured when the single-query GEMV was still thread-per-row and 5.6×
// slower than it is now — the tiled kernel only ever looked good against a baseline
// that has since been fixed. Re-measured against the current one it lost at every M
// (6.4–12.7×), so there is no longer a tiled route at all.
const batchSmallMaxM = 8

// topkWidths are the per-thread candidate capacities the register top-k kernels were
// compiled with (TKREG_SMALL/MID/BIG/HUGE in gemv_w8a8.cu), ascending. Each is the
// largest k its kernel can answer, because a thread's own stride may hold the entire
// global top-k — TestCUDATopK_kernelsAgree constructs exactly that case.
//
// The kernel names are DERIVED from the widths rather than kept in a parallel list.
// An earlier version kept both and gated that they agreed; deriving them makes a
// mis-pairing impossible to write, which is strictly better than catching it.
// TestTopKPipelineWidths still ties the derived names to the .cu source.
var topkWidths = [...]int{8, 16, 32, 64}

// topkKernelName is the entry point for one (kind, width) pair, where kind is
// "rows" (one block per query), "split" (many blocks per query) or "merge".
func topkKernelName(kind string, width int) string {
	return fmt.Sprintf("topk_%s_r%d", kind, width)
}

// topkPlan returns the index of the NARROWEST register kernel that can answer k, or -1
// for the k-pass fallback. Narrowest, because their cost is linear in the per-thread
// width and flat in k (the table is in gemv_w8a8.cu): a single widest kernel would be
// 2.3x slower at k=10, the repo's own default.
//
// Split out as a pure function, and tested as one, because the failure it guards is
// invisible to a parity test on ordinary data: routing k to a kernel that cannot hold k
// candidates still returns a full, sorted, plausible list, just missing entries that
// happened to share a thread's stride.
func topkPlan(k int) int {
	for i, w := range topkWidths {
		if k <= w {
			return i
		}
	}
	return -1
}

// topkSplitParts is how many blocks to put on ONE query's row: 1 means the one-block
// kernel, more means split-then-merge.
//
// Two independent limits, both measured at N=200k and N=500k, k=10:
//
//   - Splitting only pays while one block per query cannot fill the device. At M >= sm
//     there are already at least as many blocks as multiprocessors and the second launch
//     is pure overhead: at N=500k, M=64 the split form was 5% SLOWER than one block, and
//     at M=256 it was 48% slower. Below that the win is large — 13x at M=1, 5.4x at M=8.
//   - Each block still needs enough of the row to amortize its own k-round emit.
//     topkSplitChunk elements is where that stopped improving; at M=1, N=200k, going from
//     3125 elements per block (64 parts) to 781 (256 parts) cost 44%.
//
// and a cap on total blocks, because past ~1024 the emits outweigh the extra
// parallelism (M=32, N=500k: 32 parts 0.815 ms, 122 parts 0.90).
//
// sm comes from the driver, not from a constant — see gpu.Device.SMCount. A hardcoded 40
// would be this file's own gemmTileMinM: right on the box it was measured on, silently
// wrong everywhere else.
func topkSplitParts(M, N, sm int) int {
	if sm <= 0 {
		sm = topkSMFallback
	}
	if M >= sm {
		return 1
	}
	parts := N / topkSplitChunk
	if cap := topkSplitMaxBlocks / M; parts > cap {
		parts = cap
	}
	if parts < 1 {
		return 1
	}
	return parts
}

const (
	// Elements per block below which the per-block emit stops being amortized.
	topkSplitChunk = 4096
	// Total blocks past which more parallelism costs more than it returns.
	topkSplitMaxBlocks = 1024
	// Used only when the driver will not report a multiprocessor count. Deliberately
	// small: under-splitting costs throughput, over-splitting can cost correctness of
	// the performance claim on a device we know nothing about.
	topkSMFallback = 16
)

// topkScratch is the reused device scratch for a small top-k batch, grown on demand.
//
// WHY IT IS BOUNDED. TopKBatch's biggest allocation is the M*N score matrix; at M=256,
// N=1e6 that is 1 GB, and caching the largest batch a process ever ran would hold it for
// the process's life. So only small batches reuse, which is also where the allocation
// actually mattered: at M=1 the per-call cudaMallocs were most of the difference between
// device selection (1.05 ms) and score-then-host-select (1.18), while at M=256 they are
// noise against 21 ms of kernel.
type topkScratch struct {
	qi8, qscale, score, idx, val gpu.Buffer
	pIdx, pVal                   gpu.Buffer
	mBuf, kBuf, pBuf             gpu.Buffer
}

// topkScratchMaxM is the batch width up to which scratch is cached rather than
// allocated per call. 8 keeps the resident score matrix at 8*N floats — 32 MB at N=1e6,
// against the 1 GB a 256-batch would pin — while covering the single-query path this
// exists for.
const topkScratchMaxM = 8

// growBuf returns a buffer of at least n elements, reusing b when it is already large
// enough and reallocating otherwise. The old buffer is released, so a growing sequence
// of calls does not leak; the device ledger tracks both.
func (x *cudaI8Index) growBuf(b gpu.Buffer, n int, make func(int) gpu.Buffer) gpu.Buffer {
	if b.Len() >= n && n > 0 {
		return b
	}
	// Allocate the new buffer BEFORE releasing the old one (found while
	// porting C-04's fix to this file, same MustBuf OOM panic it is about):
	// the reverse order released the old buffer first, so a panic out of
	// `make` left the caller's field — t.qi8 etc., on the persistent
	// per-index cache TopKBatch reuses across calls — still pointing at a
	// buffer that had already been released instead of its old, valid one. A
	// later call would then reuse a freed handle. This order costs holding
	// both sizes at once for a moment; it buys getting back a still-valid old
	// buffer, untouched, on failure.
	nb := make(n)
	if b.Len() > 0 {
		x.b.dev.ReleaseBuf(b)
	}
	return nb
}

// launchTopK selects each query's top k from the [M*N] score matrix, either with one
// block per query or split across several with a merge pass (see topkSplitParts). Both
// routes return identical hits — the split is exact because the global top k is
// contained in the union of the per-chunk top k — so this is purely throughput.
//
// The k-pass kernel consumes winners in place, so scoreBuf is scratch by the time it
// returns; the register kernels leave it alone.
func (x *cudaI8Index) launchTopK(scoreBuf, idxBuf, valBuf, mBuf, kBuf gpu.Buffer, M, N, k int) error {
	block := uint32(topkBlockThreads)
	parts := topkSplitParts(M, N, x.b.sm)
	if parts <= 1 || topkPlan(k) < 0 {
		// One block per query. The k-pass fallback (topkPlan < 0) has no split form:
		// above the widest register width it is already the slow path, and splitting
		// a kernel that re-reads the row k times would multiply the partials too.
		return x.b.q.Launch(x.topkPipeline(k), gpu.LaunchConfig{
			GridX: uint32(M), GridY: 1, GridZ: 1, BlockX: block, BlockY: 1, BlockZ: 1,
		}, gpu.Arg(scoreBuf), gpu.Arg(idxBuf), gpu.Arg(valBuf),
			gpu.Arg(mBuf), gpu.Arg(x.nbuf), gpu.Arg(kBuf))
	}
	w := topkPlan(k)
	// Partials: k candidates per (query, chunk), M*parts*k against the M*N score
	// matrix they select from.
	//
	// CACHED for small batches (audit M-17). These were allocated and freed on
	// EVERY call — three device allocations, one of them an upload, and three
	// frees — on the path whose whole problem is per-call fixed cost. The
	// topkScratch struct already had pIdx/pVal/pBuf fields for exactly this and
	// nothing used them. Large batches still allocate per call, so a one-off
	// wide batch cannot pin its partials for the process's life, which is the
	// same rule the score matrix follows.
	var partIdx, partVal, pBuf gpu.Buffer
	if M <= topkScratchMaxM {
		t := &x.tk
		t.pIdx = x.growBuf(t.pIdx, M*parts*k, func(n int) gpu.Buffer { return gpu.NewBufferLenOf[int32](x.b.dev, n) })
		t.pVal = x.growBuf(t.pVal, M*parts*k, x.b.dev.NewBufferLen)
		t.pBuf = x.growBuf(t.pBuf, 1, func(int) gpu.Buffer { return gpu.NewBufferOf(x.b.dev, []uint32{0}) })
		// One element, so growBuf never resizes it; parts varies with M and N so
		// it is rewritten per call.
		if err := t.pBuf.SetU32(uint32(parts * k)); err != nil {
			return err
		}
		partIdx, partVal, pBuf = t.pIdx, t.pVal, t.pBuf
	} else {
		partIdx = gpu.NewBufferLenOf[int32](x.b.dev, M*parts*k)
		partVal = x.b.dev.NewBufferLen(M * parts * k)
		pBuf = gpu.NewBufferOf(x.b.dev, []uint32{uint32(parts * k)})
		defer func() {
			for _, b := range []gpu.Buffer{partIdx, partVal, pBuf} {
				x.b.dev.ReleaseBuf(b)
			}
		}()
	}
	if err := x.b.q.Launch(x.b.topkSplit[w], gpu.LaunchConfig{
		GridX: uint32(parts), GridY: uint32(M), GridZ: 1, BlockX: block, BlockY: 1, BlockZ: 1,
	}, gpu.Arg(scoreBuf), gpu.Arg(partIdx), gpu.Arg(partVal),
		gpu.Arg(mBuf), gpu.Arg(x.nbuf), gpu.Arg(kBuf)); err != nil {
		return err
	}
	return x.b.q.Launch(x.b.topkMerge[w], gpu.LaunchConfig{
		GridX: uint32(M), GridY: 1, GridZ: 1, BlockX: block, BlockY: 1, BlockZ: 1,
	}, gpu.Arg(partIdx), gpu.Arg(partVal), gpu.Arg(idxBuf), gpu.Arg(valBuf),
		gpu.Arg(mBuf), gpu.Arg(pBuf), gpu.Arg(kBuf))
}

// batchGridX narrows the row grid so each block sweeps several row-groups instead of
// one, amortizing the query-tile staging the kernel does before its row loop.
//
// batchRowsPerBlock is 8 because that is where it stopped paying, measured at N=200k:
// dividing the full grid by 8 landed within 0.1% of the best division at M=16, 64 and
// 256 alike, where /2 left most of the win on the table and /16 gained nothing. The
// floor keeps enough blocks to fill the device for small N — dividing a grid that was
// already smaller than the machine would trade a staging saving for idle SMs.
func batchGridX(full, planes, sm int) uint32 {
	if sm <= 0 {
		sm = topkSMFallback
	}
	gx := full / batchRowsPerBlock
	if min := (batchMinBlocks*sm + planes - 1) / planes; gx < min {
		gx = min
	}
	if gx > full {
		gx = full
	}
	if gx < 1 {
		gx = 1
	}
	return uint32(gx)
}

const (
	// Row-groups' worth of grid to collapse into each block's stride loop.
	batchRowsPerBlock = 8
	// Blocks per multiprocessor to keep regardless, across all query-tile planes.
	batchMinBlocks = 4
)

// topkBlockThreads is TKBLOCK in gemv_w8a8.cu. Every top-k kernel is written against
// it — it sets both the reduction tree depth and the stride a thread scans with — so a
// launch at any other width would silently select from a subset of the row.
const topkBlockThreads = 256

// topkPipeline picks the kernel for this k. Every one of them produces IDENTICAL hits —
// same tie-break, gated by TestCUDATopK_kernelsAgree — so this is purely throughput.
//
// Above the widest register kernel the k-pass one runs rather than declining: declining
// would send the whole M×N score matrix back across PCIe for the host to select from,
// which is the cost this path exists to avoid.
func (x *cudaI8Index) topkPipeline(k int) gpu.Pipeline {
	if i := topkPlan(k); i >= 0 {
		return x.b.topkReg[i]
	}
	return x.b.topk
}

// TopKBatch implements ann.I8TopKIndex: score the batch on the device, select each
// query's top-k THERE, and return only M*k hits.
//
// The point is the readback. ScoreBatch must copy the whole M×N score matrix to the
// host — at N=1e6, batch=256 that is ~1 GB over PCIe, and on a discrete GPU that is a
// real transfer, not the near-free UMA view Metal enjoys. Selecting on-device turns it
// into M*k.
//
// It DECLINES (returns an error, which FlatI8.QueryBatch treats as "use the scoring
// path") for small N, for k outside the range the kernel implements, and on any device
// failure. The fallback's result is identical, so declining is always safe.
//
// The device selection reproduces ann.topHits's order exactly — score DESC, index ASC
// on ties — so this returns the SAME hits the CPU would, not merely a plausible set.
func (x *cudaI8Index) TopKBatch(queries [][]float32, k int) (hits [][]ann.Hit, err error) {
	M := len(queries)
	if M == 0 {
		return nil, nil
	}
	N, K := x.n, x.dim
	// k <= 0 or k >= N is topHits's full-sort path, which this kernel does not
	// implement; below topkMinN the extra launch costs more than the readback it
	// saves. Both decline rather than approximate.
	if k <= 0 || k >= N || N < topkMinN {
		return nil, fmt.Errorf("gpu: TopKBatch declined (k=%d n=%d batch=%d)", k, N, M)
	}
	qi8 := make([]int8, M*K)
	qscale := make([]float32, M)
	for m, q := range queries {
		if len(q) != K {
			return nil, fmt.Errorf("gpu: batch query %d dim %d != index dim %d", m, len(q), K)
		}
		qscale[m] = quantizeRowInt8(q, qi8[m*K:(m+1)*K])
	}
	x.mu.Lock()
	defer x.mu.Unlock()
	defer func() {
		if r := recover(); r != nil {
			hits, err = nil, fmt.Errorf("gpu: topk scratch allocation failed: %v", r)
		}
	}()

	// Small batches reuse the per-index scratch; large ones allocate and release, so a
	// one-off wide batch cannot pin its score matrix for the process's life.
	var qi8Buf, qscaleBuf, scoreBuf, idxBuf, valBuf, mBuf, kBuf gpu.Buffer
	if M <= topkScratchMaxM {
		t := &x.tk
		t.qi8 = x.growBuf(t.qi8, M*K, func(n int) gpu.Buffer { return gpu.NewBufferOf(x.b.dev, make([]int8, n)) })
		t.qscale = x.growBuf(t.qscale, M, x.b.dev.NewBufferLen)
		t.score = x.growBuf(t.score, M*N, x.b.dev.NewBufferLen)
		t.idx = x.growBuf(t.idx, M*k, func(n int) gpu.Buffer { return gpu.NewBufferLenOf[int32](x.b.dev, n) })
		t.val = x.growBuf(t.val, M*k, x.b.dev.NewBufferLen)
		t.mBuf = x.growBuf(t.mBuf, 1, func(int) gpu.Buffer { return gpu.NewBufferOf(x.b.dev, []uint32{uint32(M)}) })
		t.kBuf = x.growBuf(t.kBuf, 1, func(int) gpu.Buffer { return gpu.NewBufferOf(x.b.dev, []uint32{uint32(k)}) })
		// ONE BATCHED UPLOAD for all four host→device transfers (audit M-17).
		//
		// This was two SetU32 round-trips plus two separate gpu.Upload calls —
		// four synchronous transfers, and since this release's C-01 fix each
		// Upload synchronizes on BOTH sides of its copy, so the scalars alone
		// cost more than the query data they accompany. UploadBatch issues every
		// copy and synchronizes ONCE, so the guarantee a caller gets is
		// identical and only the cost is amortized.
		//
		// The scalars are one element each, so growBuf never resizes them; they
		// still have to be rewritten every call, which is why they are in the
		// batch rather than set at allocation.
		mv, kv := uint32(M), uint32(k)
		if err := gpu.UploadBatch([]gpu.HostCopy{
			{Dst: t.qi8, Src: unsafe.Slice((*byte)(unsafe.Pointer(unsafe.SliceData(qi8))), len(qi8))},
			{Dst: t.qscale, Src: unsafe.Slice((*byte)(unsafe.Pointer(unsafe.SliceData(qscale))), len(qscale)*4)},
			{Dst: t.mBuf, Src: unsafe.Slice((*byte)(unsafe.Pointer(&mv)), 4)},
			{Dst: t.kBuf, Src: unsafe.Slice((*byte)(unsafe.Pointer(&kv)), 4)},
		}); err != nil {
			return nil, err
		}
		qi8Buf, qscaleBuf, scoreBuf = t.qi8, t.qscale, t.score
		idxBuf, valBuf, mBuf, kBuf = t.idx, t.val, t.mBuf, t.kBuf
	} else {
		// Registered BEFORE any of these seven allocations, not after (audit
		// C-04): a panic partway through used to leak whatever had already
		// landed, because the defer that would release it was not registered
		// yet. Only this branch's own fresh buffers — the M<=topkScratchMaxM
		// branch above aliases the persistent per-index cache in x.tk, which
		// this call must not release. ReleaseBuf ignores the zero Buffer, so
		// this is safe over the fields a panic never reached.
		defer func() {
			for _, b := range []gpu.Buffer{qi8Buf, qscaleBuf, scoreBuf, idxBuf, valBuf, mBuf, kBuf} {
				x.b.dev.ReleaseBuf(b)
			}
		}()
		qi8Buf = gpu.NewBufferOf(x.b.dev, qi8)
		qscaleBuf = gpu.NewBufferOf(x.b.dev, qscale)
		scoreBuf = x.b.dev.NewBufferLen(M * N)
		idxBuf = gpu.NewBufferLenOf[int32](x.b.dev, M*k)
		valBuf = x.b.dev.NewBufferLen(M * k)
		mBuf = gpu.NewBufferOf(x.b.dev, []uint32{uint32(M)})
		kBuf = gpu.NewBufferOf(x.b.dev, []uint32{uint32(k)})
	}
	if err := x.launchBatch(qi8Buf, qscaleBuf, scoreBuf, M, N, K); err != nil {
		return nil, err
	}
	if err := x.launchTopK(scoreBuf, idxBuf, valBuf, mBuf, kBuf, M, N, k); err != nil {
		return nil, err
	}
	if err := x.b.q.Sync(); err != nil {
		return nil, err
	}
	idx := make([]int32, M*k)
	val := make([]float32, M*k)
	if err := gpu.Download(idxBuf, idx); err != nil {
		return nil, err
	}
	if err := gpu.Download(valBuf, val); err != nil {
		return nil, err
	}
	out := make([][]ann.Hit, M)
	for m := range M {
		row := make([]ann.Hit, 0, k)
		for j := range k {
			i := idx[m*k+j]
			if i < 0 {
				break
			}
			row = append(row, ann.Hit{Index: int(i), Score: float64(val[m*k+j])})
		}
		out[m] = row
	}
	return out, nil
}

// launchBatch dispatches the batched W8A8 scoring kernel over M queries, writing
// [M*N] scores into outBuf. Both instantiations produce bit-identical results — int32
// sums are associative, and each output is exactly the value gemv_w8a8 computes for
// that query — so the choice between them is purely throughput and can never change
// a score. TestCUDAGEMM_batchMatchesQuery gates that as exact equality.
func (x *cudaI8Index) launchBatch(qi8Buf, qscaleBuf, outBuf gpu.Buffer, M, N, K int) error {
	if M == 1 {
		// A 1-query batch IS a single-query GEMV, and the dedicated kernel is the
		// faster way to run one: 0.49 ms against batch8's 0.57 at N=200k K=768,
		// because batch8 computes 8 accumulators to store 1. The layouts already
		// agree — qscaleBuf is [1] here, which is what gemv's scalar qscale binding
		// expects, and out[j] is the same [N] row.
		return x.b.q.Run1D(x.b.gemv, x.n*gemvLanes, batchBlock,
			x.codes, qi8Buf, x.scales, x.kbuf, qscaleBuf, outBuf, x.nbuf)
	}
	wide, lanes, qtile := batchPlan(M)
	p := x.b.batchSmall
	if wide {
		p = x.b.batchWide
	}
	// Grid Y is one plane per query tile. Grid X covers N rows at `lanes` threads
	// each, DIVIDED BY batchRowsPerBlock: the kernel strides over rows, so fewer
	// blocks means each one amortizes its query-tile staging over more of them.
	planes := (M + qtile - 1) / qtile
	cfg := gpu.Grid1D(N*lanes, batchBlock)
	cfg.GridX = batchGridX(int(cfg.GridX), planes, x.b.sm)
	cfg.GridY = uint32(planes)
	// The query tile lives in dynamic shared memory: QTILE rows of K bytes. At the
	// shapes this backend sees (K ≤ 1024) that is at most 16 KiB, inside the 48 KiB
	// a block gets by default.
	cfg.SharedMemBytes = uint32(qtile * K)
	mBuf := gpu.NewBufferOf(x.b.dev, []uint32{uint32(M)})
	defer x.b.dev.ReleaseBuf(mBuf)
	return x.b.q.Launch(p, cfg,
		gpu.Arg(x.codes), gpu.Arg(qi8Buf), gpu.Arg(x.scales), gpu.Arg(x.kbuf),
		gpu.Arg(qscaleBuf), gpu.Arg(outBuf), gpu.Arg(x.nbuf), gpu.Arg(mBuf))
}

// batchPlan picks the batch kernel for M and returns the geometry constants THAT
// kernel was compiled with. It is a separate pure function, and tested as one,
// because pairing a kernel with the wrong constants is the failure mode no parity
// test can see: too many lanes over-launches and the row-bound check quietly absorbs
// it (2x the blocks, half discarded), while too few under-launches and the tail of
// the corpus is never scored at all — and the second one still returns a full,
// plausible top-k drawn from the rows it did reach.
func batchPlan(M int) (wide bool, lanes, qtile int) {
	if M > batchSmallMaxM {
		return true, batchLanesWide, batchQTileWide
	}
	return false, batchLanesSmall, batchQTileSmall
}

// The (LANES, QTILE) constants each batch kernel was compiled with. They are
// duplicated from gemv_w8a8.cu because the launch geometry depends on them and PTX
// carries no way to ask; TestBatchKernelConstantsMatchSource keeps the two in step.
const (
	// gemvLanes mirrors GEMV_LANES in gemv_w8a8.cu — the threads that cooperate on one
	// corpus row in the single-query kernel, and so the multiplier on its launch width.
	// A value larger than the kernel's over-launches (absorbed by the row bound check);
	// smaller silently leaves the tail of the corpus unscored.
	gemvLanes = 16

	batchLanesSmall = 8
	batchQTileSmall = 8
	batchLanesWide  = 4
	batchQTileWide  = 16
	batchBlock      = 256
)
