package encoder

// Generated embedder-coverage table (docs/task-embedding-coverage.md,
// "Coverage claim, generated not hand-maintained").
//
// A hand-maintained support list rots, so this one is defended three ways:
//
//  1. FRESHNESS — the table is rendered from the registry below and diffed against
//     the committed docs/embedder-coverage.md. Editing the doc by hand, or adding a
//     row without regenerating, turns the build red. Model-free, so it runs in CI.
//     Regenerate with `go test ./encoder -run EmbedderCoverage -update`.
//  2. GATE EXISTENCE — every row names the parity test that certifies it, and that
//     function must actually exist in this package's sources. You cannot claim a
//     model is validated without a gate.
//  3. PROPERTY TRUTH — when the checkpoint is present locally, the declared pooling
//     and dimensions are checked against what the loader actually derives from the
//     real files. CI skips (weights are gitignored); a developer with the models
//     gets the claims verified rather than trusted.

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"strings"
	"testing"
)

const coveragePath = "../docs/embedder-coverage.md"
const coverageHeader = "<!-- GENERATED by go test ./encoder -run EmbedderCoverage -update — DO NOT EDIT -->"

var updateCoverage = flag.Bool("update", false, "rewrite docs/embedder-coverage.md")

// loaderKind is which entry point loads a checkpoint — the thing that determines
// which forward runs, so it belongs in the published table.
type loaderKind int

const (
	loaderBERT  loaderKind = iota // LoadBERT: learned-absolute positions, GELU
	loaderNomic                   // Load/LoadWeightsFromFS: nomic-bert, RoPE
)

func (k loaderKind) String() string {
	if k == loaderBERT {
		return "LoadBERT"
	}
	return "Load"
}

// covRow is one certified embedder. Pooling/Dims are claims verified against the
// real checkpoint by TestEmbedderCoverage_propertiesMatchCheckpoints.
type covRow struct {
	Model     string     // HF id
	Dir       string     // testdata dir (gitignored; tests skip without it)
	Loader    loaderKind //
	Family    string     // architecture, as the loader sees it
	Pooling   string     // "mean" | "cls" | "—" (no pooling head)
	Tokenizer string     // "WordPiece" | "Unigram"
	Dims      int        //
	Gate      string     // the test function that certifies it
	Note      string     // what makes this row worth having
}

// coverageRows is the single source of truth for the published table. Keep it in
// certification order — each row was landed by the gate named in it.
var coverageRows = []covRow{
	{"sentence-transformers/all-MiniLM-L6-v2", "../testdata/minilm-model", loaderBERT,
		"BERT", "mean", "WordPiece", 384, "TestBERT_parity",
		"the baseline BERT embedder"},
	{"nomic-ai/CodeRankEmbed", "../testdata/encoder-model", loaderNomic,
		"nomic-bert (RoPE, SwiGLU)", "cls", "WordPiece", 768, "TestGoldenFixture_cosine",
		"the original rotary/SwiGLU path"},
	{"BAAI/bge-small-en-v1.5", "../testdata/bge-small", loaderBERT,
		"BERT", "cls", "WordPiece", 384, "TestBGE_parity",
		"CLS pooling read from 1_Pooling, not assumed"},
	{"nomic-ai/nomic-embed-text-v1.5", "../testdata/nomic-embed", loaderNomic,
		"nomic-bert (RoPE, SwiGLU)", "mean", "WordPiece", 768, "TestNomicEmbed_parity",
		"declared mean pooling on the rotary path"},
	{"FacebookAI/xlm-roberta-base", "../testdata/xlm-roberta-base", loaderBERT,
		"XLM-R", "—", "Unigram", 768, "TestXLMR_forwardParity",
		"position-id offset (pad+1); bare LM, so forward-only"},
	{"intfloat/multilingual-e5-base", "../testdata/multilingual-e5-base", loaderBERT,
		"XLM-R", "mean", "Unigram", 768, "TestMultilingualE5_parity",
		"first multilingual embedder certified full-stack"},
	{"BAAI/bge-m3", "../testdata/bge-m3", loaderBERT,
		"XLM-R", "cls", "Unigram", 1024, "TestBGEM3_parity",
		"CLS multilingual; bare-Metaspace tokenizer variant"},
	{"nomic-ai/nomic-embed-text-v2-moe", "../testdata/nomic-moe", loaderNomic,
		"nomic-bert + MoE (top-2 of 8)", "mean", "Unigram", 768, "TestNomicMoE_parity",
		"mixture-of-experts FFN on odd layers"},
}

func buildCoverageMarkdown() []byte {
	var b bytes.Buffer
	b.WriteString(coverageHeader + "\n\n")
	b.WriteString("# aikit embedder coverage\n\n")
	b.WriteString("Every model below is certified against its HuggingFace reference at **cosine\n")
	b.WriteString("≥ 0.9999** (all currently land at 1.000000) with a hidden-state gate and a\n")
	b.WriteString("break-it-first check — perturb the pooling, position offset, or routing and the\n")
	b.WriteString("gate must go red. A model is not listed until its gate is green.\n\n")
	b.WriteString("Generated from the registry in `encoder/coverage_test.go`, which is itself\n")
	b.WriteString("checked against the real checkpoints (declared pooling and dimensions are read\n")
	b.WriteString("back from the loader when the weights are present). Regenerate with\n")
	b.WriteString("`go test ./encoder -run EmbedderCoverage -update`.\n\n")
	b.WriteString("| Model | Architecture | Loader | Pooling | Tokenizer | Dims | Gate |\n")
	b.WriteString("|---|---|---|---|---|---|---|\n")
	for _, r := range coverageRows {
		fmt.Fprintf(&b, "| `%s` | %s | `%s` | %s | %s | %d | `%s` |\n",
			r.Model, r.Family, r.Loader, r.Pooling, r.Tokenizer, r.Dims, r.Gate)
	}
	b.WriteString("\n## Why each row is here\n\n")
	for _, r := range coverageRows {
		fmt.Fprintf(&b, "- **`%s`** — %s\n", r.Model, r.Note)
	}
	b.WriteString("\n## Not in this table\n\n")
	b.WriteString("`encoder` also ships SPLADE (sparse lexical) and a cross-encoder reranker, both\n")
	b.WriteString("parity-gated in their own tests. They are excluded here because \"pooling\" and a\n")
	b.WriteString("single dense width do not describe them.\n\n")
	b.WriteString("The checkpoints themselves are gitignored (they are large); the gates skip when a\n")
	b.WriteString("model is absent, so CI runs the freshness check without weights.\n")
	return b.Bytes()
}

// TestEmbedderCoverage_fresh is the staleness gate: adding, removing, or editing a
// row must regenerate docs/embedder-coverage.md or the build goes red. `-update`
// rewrites it. Model-free, so this runs in CI.
func TestEmbedderCoverage_fresh(t *testing.T) {
	md := buildCoverageMarkdown()
	if *updateCoverage {
		if err := os.WriteFile(coveragePath, md, 0o644); err != nil {
			t.Fatalf("write %s: %v", coveragePath, err)
		}
		t.Logf("wrote %s (%d rows)", coveragePath, len(coverageRows))
		return
	}
	got, err := os.ReadFile(coveragePath)
	if err != nil {
		t.Fatalf("read %s: %v (regenerate: go test ./encoder -run EmbedderCoverage -update)", coveragePath, err)
	}
	if !bytes.Equal(bytes.TrimSpace(got), bytes.TrimSpace(md)) {
		t.Fatalf("%s is stale — regenerate: go test ./encoder -run EmbedderCoverage -update", coveragePath)
	}
}

// TestEmbedderCoverage_gatesExist enforces that every claim in the table is backed
// by a real test function. Without this, a row could assert "validated" for a model
// nothing actually checks — the exact way a support list rots.
func TestEmbedderCoverage_gatesExist(t *testing.T) {
	entries, err := os.ReadDir(".")
	if err != nil {
		t.Fatal(err)
	}
	var srcs []byte
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), "_test.go") {
			continue
		}
		b, err := os.ReadFile(e.Name())
		if err != nil {
			t.Fatal(err)
		}
		srcs = append(srcs, b...)
	}
	for _, r := range coverageRows {
		if !bytes.Contains(srcs, []byte("func "+r.Gate+"(")) {
			t.Errorf("%s: gate %q is not a test function in this package", r.Model, r.Gate)
		}
	}
}

// TestEmbedderCoverage_propertiesMatchCheckpoints verifies the table's claims
// against the actual checkpoints, so pooling/dims can't drift from reality. Skips
// per-row when a model isn't present (CI); a developer with the weights gets every
// present row checked.
func TestEmbedderCoverage_propertiesMatchCheckpoints(t *testing.T) {
	checked := 0
	for _, r := range coverageRows {
		if _, err := os.Stat(r.Dir + "/model.safetensors"); err != nil {
			continue
		}
		t.Run(r.Model, func(t *testing.T) {
			checked++
			var gotPool string
			var gotDims int
			switch r.Loader {
			case loaderBERT:
				b, err := LoadBERT(r.Dir)
				if err != nil {
					t.Fatalf("LoadBERT: %v", err)
				}
				gotPool, gotDims = string(b.pool), b.cfg.Hidden
			default:
				m, err := Load(r.Dir)
				if err != nil {
					t.Fatalf("Load: %v", err)
				}
				gotPool, gotDims = string(m.weights.Cfg.pooling), m.HiddenDim()
			}
			if gotDims != r.Dims {
				t.Errorf("dims: table says %d, checkpoint says %d", r.Dims, gotDims)
			}
			// "—" marks a checkpoint with no pooling head (bare LM): the loader
			// falls back to a default, so there is nothing to verify.
			if r.Pooling != "—" && gotPool != r.Pooling {
				t.Errorf("pooling: table says %q, checkpoint says %q", r.Pooling, gotPool)
			}
		})
	}
	t.Logf("verified %d/%d rows against local checkpoints", checked, len(coverageRows))
}
