#!/usr/bin/env python3
"""gen_iq_grids.py — emit embed/iq_grids.go: the IQ2_S / IQ3_S dequant grid
codebooks, dumped verbatim from llama.cpp's gguf Python reference so they are
byte-exact (no hand transcription of the ggml constant tables).

IQ2_S uses a 1024×8 int8 grid (magnitudes in {8,25,43}); IQ3_S a 512×4 int8 grid
(odd magnitudes 1..15). Both are sign-free here — the per-element sign comes from
the block's packed sign bits at dequant time. Stored base64 (values fit in a byte)
and decoded once at package init.

Usage:  .venv/bin/python scripts/gen_iq_grids.py
"""
from __future__ import annotations

import base64
import textwrap
from pathlib import Path

import numpy as np
from gguf.quants import dequantize, IQ2_S, IQ3_S
from gguf.constants import GGMLQuantizationType as T

REPO_ROOT = Path(__file__).resolve().parent.parent


def grid_bytes(cls, qtype, type_size: int) -> bytes:
    dequantize(np.zeros(type_size, dtype=np.uint8), qtype)  # populate cls.grid
    g = np.asarray(cls.grid).reshape(-1).astype(np.int64)
    assert g.min() >= 0 and g.max() <= 127, (int(g.min()), int(g.max()))
    return bytes(int(x) for x in g)


def wrap_b64(b: bytes) -> str:
    s = base64.b64encode(b).decode()
    return "\n".join('\t"%s" +' % line for line in textwrap.wrap(s, 96)).rstrip(" +")


def main() -> int:
    iq2 = grid_bytes(IQ2_S, T.IQ2_S, 82)   # 1024*8 = 8192
    iq3 = grid_bytes(IQ3_S, T.IQ3_S, 110)  # 512*4  = 2048
    assert len(iq2) == 8192 and len(iq3) == 2048, (len(iq2), len(iq3))

    out = f'''// Code generated by scripts/gen_iq_grids.py; DO NOT EDIT.
// IQ2_S / IQ3_S dequant codebooks, dumped byte-exact from llama.cpp's gguf
// Python reference (gguf.quants). Values are sign-free magnitudes; the per-element
// sign is applied from each block's packed sign bits at dequant time.

package embed

import "encoding/base64"

// iq2sGrid is the IQ2_S codebook: 1024 entries of 8 int8 magnitudes ({{8,25,43}}).
var iq2sGrid = decodeGrid(iq2sGridB64)

// iq3sGrid is the IQ3_S codebook: 512 entries of 4 int8 magnitudes (odd 1..15).
var iq3sGrid = decodeGrid(iq3sGridB64)

func decodeGrid(s string) []int8 {{
\tb, err := base64.StdEncoding.DecodeString(s)
\tif err != nil {{
\t\tpanic("embed: bad IQ grid: " + err.Error())
\t}}
\tg := make([]int8, len(b))
\tfor i, v := range b {{
\t\tg[i] = int8(v)
\t}}
\treturn g
}}

const iq2sGridB64 = "" +
{wrap_b64(iq2)}

const iq3sGridB64 = "" +
{wrap_b64(iq3)}
'''
    dst = REPO_ROOT / "embed" / "iq_grids.go"
    dst.write_text(out)
    print(f"wrote {dst.relative_to(REPO_ROOT)} (iq2s {len(iq2)} bytes, iq3s {len(iq3)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
