// NEON f64 G=6 grouped ports of the acc64 attention kernels (R13, goinfer's
// docs/tasks/red-october.md). G=6 is the 1.5B's real GQA group size, the
// brief's own registered decision shape; other G fall back to the plain Go
// MatmulAVAcc64Group/MatmulQKAcc64Group (see attn_acc64_group_arm64.go).
//
// avAcc64NEON8G6 — one 8-dim block of V, all G=6 queries' scores at once:
//   dst[g][d] = float32(Σ_s float64(scores[g][s]) · float64(V[s][d])),
//   key-ascending, d = 0..7 within this block.
// qkAcc64NEON8G6 — see attn_acc64_group_arm64.s's second half (appended once
// built and gated the same way).
//
// REGISTER BUDGET (red-october.md's own analysis): "AV at 8 dims × G=6 is 24
// accumulators + 4 V + 1 score = 29" of NEON's 32. V0-V23 hold the 24
// accumulators (one f64x2 register per (query g, dim-pair dp), lane = dim
// within the pair, index = g*4+dp, dp=0..3 covering dims (0,1)(2,3)(4,5)(6,7)
// of this block) — this is the SAME per-query accumulator convention
// attn_acc64_arm64.s's avAcc64NEON32 already uses (one register per dim-pair,
// lane = dim), just replicated across G queries instead of G=1. V26-V29 hold
// the block's V row widened once per key (4 registers, shared read for the
// whole g loop — the entire point of grouping, matching the identity
// argument matmul_av_acc64_group.go's header already makes: only the loop
// NESTING changes, key-ascending order per (g,dim) is unchanged). V31 holds
// one query's score widened per (key, g) — same scalar-widen convention
// avAcc64NEON32 already uses. V24, V25, V30 are unused (29 of 32 in use,
// matching the brief's own count).
//
// BIT-IDENTICAL to MatmulAVAcc64Group / to G separate MatmulAVAcc64 calls, by
// the same "order of operations applied to ONE accumulator, not what
// unrelated accumulators do in between" argument attn_acc64_arm64.s's own
// header already makes, now applied across queries instead of just across
// dims: each (g, dim) accumulator here receives exactly the same
// key-ascending fold MatmulAVAcc64 would compute for that head alone.
// TestAVAcc64NEON8G6_matchesGo is the check.
//
// No zip needed here (unlike QK's key-interleaving) — each register's two f64
// lanes are two CONSECUTIVE dims of the SAME key, not two different keys, so
// V's raw f32 quad widens directly via FCVTL (lower 2) / FCVTL2 (upper 2),
// including in place (Vd==Vn is architecturally valid for a single
// convert — the source read completes before the result is written).
//
// Encodings, same convention as attn_acc64_arm64.s (its own header has the
// full derivation and worked checks):
//   FCVTL   Vd.2D, Vn.2S            = 0x0E617800 | Rn<<5 | Rd
//   FCVTL2  Vd.2D, Vn.4S            = 0x4E617800 | Rn<<5 | Rd
//   FCVTN   Vd.2S, Vn.2D            = 0x0E616800 | Rn<<5 | Rd
//   FCVTN2  Vd.4S, Vn.2D            = 0x4E616800 | Rn<<5 | Rd
//   FMLA    Vd.2D, Vn.2D, Vm.D[i]   = 0x4FC01000 | M<<20 | Rm<<16 | i<<11 | Rn<<5 | Rd
//     (M=1, Rm&0xF in the Rm field, when the by-element source is V16-V31)
// Generated by a small Python encoder (scratchpad/gen_av.py this session) to
// avoid hand hex arithmetic; spot-checked by hand against the formulas above.

#include "textflag.h"

// func avAcc64NEON8G6(scores *float32, scoresRowStrideBytes int, vals *float32, nKeys int, rowStrideBytes int, dst *float32, dstRowStrideBytes int)
TEXT ·avAcc64NEON8G6(SB), NOSPLIT, $0-56
	MOVD scores+0(FP), R0
	MOVD scoresRowStrideBytes+8(FP), R1
	MOVD vals+16(FP), R2
	MOVD nKeys+24(FP), R3
	MOVD rowStrideBytes+32(FP), R4
	MOVD dst+40(FP), R5
	MOVD dstRowStrideBytes+48(FP), R6

	MOVD R0, R7                 // 6 score row pointers, scoresRowStrideBytes apart
	ADD  R1, R7, R8
	ADD  R1, R8, R9
	ADD  R1, R9, R10
	ADD  R1, R10, R11
	ADD  R1, R11, R12

	VEOR V0.B16, V0.B16, V0.B16
	VEOR V1.B16, V1.B16, V1.B16
	VEOR V2.B16, V2.B16, V2.B16
	VEOR V3.B16, V3.B16, V3.B16
	VEOR V4.B16, V4.B16, V4.B16
	VEOR V5.B16, V5.B16, V5.B16
	VEOR V6.B16, V6.B16, V6.B16
	VEOR V7.B16, V7.B16, V7.B16
	VEOR V8.B16, V8.B16, V8.B16
	VEOR V9.B16, V9.B16, V9.B16
	VEOR V10.B16, V10.B16, V10.B16
	VEOR V11.B16, V11.B16, V11.B16
	VEOR V12.B16, V12.B16, V12.B16
	VEOR V13.B16, V13.B16, V13.B16
	VEOR V14.B16, V14.B16, V14.B16
	VEOR V15.B16, V15.B16, V15.B16
	VEOR V16.B16, V16.B16, V16.B16
	VEOR V17.B16, V17.B16, V17.B16
	VEOR V18.B16, V18.B16, V18.B16
	VEOR V19.B16, V19.B16, V19.B16
	VEOR V20.B16, V20.B16, V20.B16
	VEOR V21.B16, V21.B16, V21.B16
	VEOR V22.B16, V22.B16, V22.B16
	VEOR V23.B16, V23.B16, V23.B16
	CBZ  R3, avg6store

avg6key:
	VLD1 (R2), [V26.S4]        // dims 0-3 raw
	ADD  $16, R2, R13
	VLD1 (R13), [V28.S4]       // dims 4-7 raw
	WORD $0x4e617b5b          // FCVTL2 V27.2D, V26.4S   dims 2,3
	WORD $0x0e617b5a          // FCVTL  V26.2D, V26.2S   dims 0,1 (in place)
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   dims 6,7
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   dims 4,5 (in place)

	MOVWU.P 4(R7), R14      // score g=0
	FMOVS   R14, F30
	FCVTSD  F30, F31            // V31.D[0] = score
	WORD $0x4fdf1340          // FMLA V0.2D, V26.2D, V31.D[0]
	WORD $0x4fdf1361          // FMLA V1.2D, V27.2D, V31.D[0]
	WORD $0x4fdf1382          // FMLA V2.2D, V28.2D, V31.D[0]
	WORD $0x4fdf13a3          // FMLA V3.2D, V29.2D, V31.D[0]

	MOVWU.P 4(R8), R14      // score g=1
	FMOVS   R14, F30
	FCVTSD  F30, F31            // V31.D[0] = score
	WORD $0x4fdf1344          // FMLA V4.2D, V26.2D, V31.D[0]
	WORD $0x4fdf1365          // FMLA V5.2D, V27.2D, V31.D[0]
	WORD $0x4fdf1386          // FMLA V6.2D, V28.2D, V31.D[0]
	WORD $0x4fdf13a7          // FMLA V7.2D, V29.2D, V31.D[0]

	MOVWU.P 4(R9), R14      // score g=2
	FMOVS   R14, F30
	FCVTSD  F30, F31            // V31.D[0] = score
	WORD $0x4fdf1348          // FMLA V8.2D, V26.2D, V31.D[0]
	WORD $0x4fdf1369          // FMLA V9.2D, V27.2D, V31.D[0]
	WORD $0x4fdf138a          // FMLA V10.2D, V28.2D, V31.D[0]
	WORD $0x4fdf13ab          // FMLA V11.2D, V29.2D, V31.D[0]

	MOVWU.P 4(R10), R14      // score g=3
	FMOVS   R14, F30
	FCVTSD  F30, F31            // V31.D[0] = score
	WORD $0x4fdf134c          // FMLA V12.2D, V26.2D, V31.D[0]
	WORD $0x4fdf136d          // FMLA V13.2D, V27.2D, V31.D[0]
	WORD $0x4fdf138e          // FMLA V14.2D, V28.2D, V31.D[0]
	WORD $0x4fdf13af          // FMLA V15.2D, V29.2D, V31.D[0]

	MOVWU.P 4(R11), R14      // score g=4
	FMOVS   R14, F30
	FCVTSD  F30, F31            // V31.D[0] = score
	WORD $0x4fdf1350          // FMLA V16.2D, V26.2D, V31.D[0]
	WORD $0x4fdf1371          // FMLA V17.2D, V27.2D, V31.D[0]
	WORD $0x4fdf1392          // FMLA V18.2D, V28.2D, V31.D[0]
	WORD $0x4fdf13b3          // FMLA V19.2D, V29.2D, V31.D[0]

	MOVWU.P 4(R12), R14      // score g=5
	FMOVS   R14, F30
	FCVTSD  F30, F31            // V31.D[0] = score
	WORD $0x4fdf1354          // FMLA V20.2D, V26.2D, V31.D[0]
	WORD $0x4fdf1375          // FMLA V21.2D, V27.2D, V31.D[0]
	WORD $0x4fdf1396          // FMLA V22.2D, V28.2D, V31.D[0]
	WORD $0x4fdf13b7          // FMLA V23.2D, V29.2D, V31.D[0]

	ADD  R4, R2, R2             // next key row
	SUBS $1, R3, R3
	BNE  avg6key

avg6store:
	WORD $0x0e61681a          // FCVTN  V26.2S, V0.2D   dims 0,1 -> f32
	WORD $0x4e61683a          // FCVTN2 V26.4S, V1.2D   dims 2,3
	WORD $0x0e61685b          // FCVTN  V27.2S, V2.2D   dims 4,5 -> f32
	WORD $0x4e61687b          // FCVTN2 V27.4S, V3.2D   dims 6,7
	MOVD R5, R15
	VST1.P [V26.S4], 16(R15)
	VST1   [V27.S4], (R15)
	ADD  R6, R5, R5

	WORD $0x0e61689a          // FCVTN  V26.2S, V4.2D   dims 0,1 -> f32
	WORD $0x4e6168ba          // FCVTN2 V26.4S, V5.2D   dims 2,3
	WORD $0x0e6168db          // FCVTN  V27.2S, V6.2D   dims 4,5 -> f32
	WORD $0x4e6168fb          // FCVTN2 V27.4S, V7.2D   dims 6,7
	MOVD R5, R15
	VST1.P [V26.S4], 16(R15)
	VST1   [V27.S4], (R15)
	ADD  R6, R5, R5

	WORD $0x0e61691a          // FCVTN  V26.2S, V8.2D   dims 0,1 -> f32
	WORD $0x4e61693a          // FCVTN2 V26.4S, V9.2D   dims 2,3
	WORD $0x0e61695b          // FCVTN  V27.2S, V10.2D   dims 4,5 -> f32
	WORD $0x4e61697b          // FCVTN2 V27.4S, V11.2D   dims 6,7
	MOVD R5, R15
	VST1.P [V26.S4], 16(R15)
	VST1   [V27.S4], (R15)
	ADD  R6, R5, R5

	WORD $0x0e61699a          // FCVTN  V26.2S, V12.2D   dims 0,1 -> f32
	WORD $0x4e6169ba          // FCVTN2 V26.4S, V13.2D   dims 2,3
	WORD $0x0e6169db          // FCVTN  V27.2S, V14.2D   dims 4,5 -> f32
	WORD $0x4e6169fb          // FCVTN2 V27.4S, V15.2D   dims 6,7
	MOVD R5, R15
	VST1.P [V26.S4], 16(R15)
	VST1   [V27.S4], (R15)
	ADD  R6, R5, R5

	WORD $0x0e616a1a          // FCVTN  V26.2S, V16.2D   dims 0,1 -> f32
	WORD $0x4e616a3a          // FCVTN2 V26.4S, V17.2D   dims 2,3
	WORD $0x0e616a5b          // FCVTN  V27.2S, V18.2D   dims 4,5 -> f32
	WORD $0x4e616a7b          // FCVTN2 V27.4S, V19.2D   dims 6,7
	MOVD R5, R15
	VST1.P [V26.S4], 16(R15)
	VST1   [V27.S4], (R15)
	ADD  R6, R5, R5

	WORD $0x0e616a9a          // FCVTN  V26.2S, V20.2D   dims 0,1 -> f32
	WORD $0x4e616aba          // FCVTN2 V26.4S, V21.2D   dims 2,3
	WORD $0x0e616adb          // FCVTN  V27.2S, V22.2D   dims 4,5 -> f32
	WORD $0x4e616afb          // FCVTN2 V27.4S, V23.2D   dims 6,7
	MOVD R5, R15
	VST1.P [V26.S4], 16(R15)
	VST1   [V27.S4], (R15)

	RET

// qkAcc64NEON8G6 — one block of 8 keys, all G=6 queries at once:
//   dst[g][j] = float32(Σ_d float64(q[g][d]) · float64(K[j][d])), d-ascending,
//   j = 0..7 within this block.
//
// REGISTER BUDGET: "QK at 8 keys × G=6 is 24 accumulators + 4 widened K + 2
// q = 30" of NEON's 32. V0-V23 hold the 24 accumulators — one f64x2 register
// per (query g, key-pair kp), lane = key within the pair, index = g*4+kp,
// kp=0..3 covering keys (0,1)(2,3)(4,5)(6,7) — the same per-query accumulator
// convention attn_acc64_arm64.s's qkAcc64NEON16 already uses (one register
// per key-pair, lane = key), replicated across G queries instead of G=1.
//
// Per d-quad, per key-pair: K is loaded and widened ONCE (4 registers,
// V24/V25/V26/V27 — see the in-place-reuse comments inline; NOT V16-19,
// because those numbers collide with accumulator indices g=4's four
// key-pairs, acc(4,kp)=16..19, which would clobber a live accumulator with a
// raw K load mid-block) and shared across all 6 queries' FMLA chains — the
// entire point of grouping, same identity argument matmul_qk_acc64_group.go's
// header already makes (only the loop NESTING changes; each (g,key)
// accumulator still receives the exact d-ascending fold MatmulQKAcc64 would
// compute for that head alone). q is re-widened per (kp, g) into 2 transient
// registers (V28/V29, same in-place trick as the K side) — 4x redundant
// across the 4 key-pairs, deliberately: q is tiny (one hd-wide row, stays
// L1-resident) so cheaply re-deriving it 4x is a better trade than spilling
// widened-K to make room for 6 simultaneously-resident widened-q rows, which
// the register count does not allow. TestQKAcc64NEON8G6_matchesGo is the
// check for the whole thing, not just the argument.
//
// Q, K, and dst pointer bookkeeping: 8 K row pointers and 6 q row pointers
// are (re)derived by chained ADD at the top of every block (K rows advance
// via the load's own post-increment through a block's d-quad sweep; q rows
// only advance once per d-quad, by an explicit ADD after the key-pair×query
// unrolled body, since the SAME q address is read 4x — once per key-pair —
// within one d-quad). dst is [G,N] row-major (unlike AV's [G,hd]): R22 tracks
// this block's query-0 COLUMN offset and is left unmodified through the
// store phase (only R26, a disposable copy, walks the 6 query rows), so
// R22+32 is the next block's column offset without any rewind arithmetic.
//
// Same WORD-encoding conventions as attn_acc64_group_arm64.s's AV kernel
// above (and attn_acc64_arm64.s's own header); ZIP1/ZIP2 additionally used
// here (attn_acc64_arm64.s's header has their derivation). Generated by a
// small Python encoder (scratchpad/gen_qk.py this session).


// func qkAcc64NEON8G6(q *float32, qStrideBytes int, rows *float32, rowStrideBytes int, k4 int, nBlocks int, dst *float32, dstRowStrideBytes int)

// func qkAcc64NEON8G6(q *float32, qStrideBytes int, rows *float32, rowStrideBytes int, k4 int, nBlocks int, dst *float32, dstRowStrideBytes int)

// func qkAcc64NEON8G6(q *float32, qStrideBytes int, rows *float32, rowStrideBytes int, k4 int, nBlocks int, dst *float32, dstRowStrideBytes int)
TEXT ·qkAcc64NEON8G6(SB), NOSPLIT, $0-64
	MOVD q+0(FP), R0
	MOVD qStrideBytes+8(FP), R1
	MOVD rows+16(FP), R2
	MOVD rowStrideBytes+24(FP), R3
	MOVD k4+32(FP), R4
	MOVD nBlocks+40(FP), R21
	MOVD dst+48(FP), R22
	MOVD dstRowStrideBytes+56(FP), R23

qkg6block:
	MOVD R2, R5
	ADD  R3, R5, R6
	ADD  R3, R6, R7
	ADD  R3, R7, R8
	ADD  R3, R8, R9
	ADD  R3, R9, R10
	ADD  R3, R10, R11
	ADD  R3, R11, R12

	MOVD R0, R14
	ADD  R1, R14, R15
	ADD  R1, R15, R16
	ADD  R1, R16, R17
	ADD  R1, R17, R19
	ADD  R1, R19, R20

	VEOR V0.B16, V0.B16, V0.B16
	VEOR V1.B16, V1.B16, V1.B16
	VEOR V2.B16, V2.B16, V2.B16
	VEOR V3.B16, V3.B16, V3.B16
	VEOR V4.B16, V4.B16, V4.B16
	VEOR V5.B16, V5.B16, V5.B16
	VEOR V6.B16, V6.B16, V6.B16
	VEOR V7.B16, V7.B16, V7.B16
	VEOR V8.B16, V8.B16, V8.B16
	VEOR V9.B16, V9.B16, V9.B16
	VEOR V10.B16, V10.B16, V10.B16
	VEOR V11.B16, V11.B16, V11.B16
	VEOR V12.B16, V12.B16, V12.B16
	VEOR V13.B16, V13.B16, V13.B16
	VEOR V14.B16, V14.B16, V14.B16
	VEOR V15.B16, V15.B16, V15.B16
	VEOR V16.B16, V16.B16, V16.B16
	VEOR V17.B16, V17.B16, V17.B16
	VEOR V18.B16, V18.B16, V18.B16
	VEOR V19.B16, V19.B16, V19.B16
	VEOR V20.B16, V20.B16, V20.B16
	VEOR V21.B16, V21.B16, V21.B16
	VEOR V22.B16, V22.B16, V22.B16
	VEOR V23.B16, V23.B16, V23.B16

	MOVD R4, R24                 // d-quad counter for this block

qkg6quad:
	// key-pair 0: keys 0,1
	VLD1.P 16(R5), [V24.S4]
	VLD1.P 16(R6), [V25.S4]
	WORD $0x4e993b1a          // ZIP1 V26.4S, V24.4S, V25.4S
	WORD $0x4e997b1b          // ZIP2 V27.4S, V24.4S, V25.4S
	WORD $0x4e617b58          // FCVTL2 V24.2D, V26.4S   d1 pair (reuse dead raw-A)
	WORD $0x0e617b5a          // FCVTL  V26.2D, V26.2S   d0 pair (in place)
	WORD $0x4e617b79          // FCVTL2 V25.2D, V27.4S   d3 pair (reuse dead raw-B)
	WORD $0x0e617b7b          // FCVTL  V27.2D, V27.2S   d2 pair (in place)
	VLD1 (R14), [V28.S4]      // q[0] quad, kp=0
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc1340          // FMLA V0.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b00          // FMLA V0.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd1360          // FMLA V0.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b20          // FMLA V0.2D, V25.2D, V29.D[1]   d3
	VLD1 (R15), [V28.S4]      // q[1] quad, kp=0
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc1344          // FMLA V4.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b04          // FMLA V4.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd1364          // FMLA V4.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b24          // FMLA V4.2D, V25.2D, V29.D[1]   d3
	VLD1 (R16), [V28.S4]      // q[2] quad, kp=0
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc1348          // FMLA V8.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b08          // FMLA V8.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd1368          // FMLA V8.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b28          // FMLA V8.2D, V25.2D, V29.D[1]   d3
	VLD1 (R17), [V28.S4]      // q[3] quad, kp=0
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc134c          // FMLA V12.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b0c          // FMLA V12.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd136c          // FMLA V12.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b2c          // FMLA V12.2D, V25.2D, V29.D[1]   d3
	VLD1 (R19), [V28.S4]      // q[4] quad, kp=0
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc1350          // FMLA V16.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b10          // FMLA V16.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd1370          // FMLA V16.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b30          // FMLA V16.2D, V25.2D, V29.D[1]   d3
	VLD1 (R20), [V28.S4]      // q[5] quad, kp=0
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc1354          // FMLA V20.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b14          // FMLA V20.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd1374          // FMLA V20.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b34          // FMLA V20.2D, V25.2D, V29.D[1]   d3

	// key-pair 1: keys 2,3
	VLD1.P 16(R7), [V24.S4]
	VLD1.P 16(R8), [V25.S4]
	WORD $0x4e993b1a          // ZIP1 V26.4S, V24.4S, V25.4S
	WORD $0x4e997b1b          // ZIP2 V27.4S, V24.4S, V25.4S
	WORD $0x4e617b58          // FCVTL2 V24.2D, V26.4S   d1 pair (reuse dead raw-A)
	WORD $0x0e617b5a          // FCVTL  V26.2D, V26.2S   d0 pair (in place)
	WORD $0x4e617b79          // FCVTL2 V25.2D, V27.4S   d3 pair (reuse dead raw-B)
	WORD $0x0e617b7b          // FCVTL  V27.2D, V27.2S   d2 pair (in place)
	VLD1 (R14), [V28.S4]      // q[0] quad, kp=1
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc1341          // FMLA V1.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b01          // FMLA V1.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd1361          // FMLA V1.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b21          // FMLA V1.2D, V25.2D, V29.D[1]   d3
	VLD1 (R15), [V28.S4]      // q[1] quad, kp=1
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc1345          // FMLA V5.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b05          // FMLA V5.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd1365          // FMLA V5.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b25          // FMLA V5.2D, V25.2D, V29.D[1]   d3
	VLD1 (R16), [V28.S4]      // q[2] quad, kp=1
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc1349          // FMLA V9.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b09          // FMLA V9.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd1369          // FMLA V9.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b29          // FMLA V9.2D, V25.2D, V29.D[1]   d3
	VLD1 (R17), [V28.S4]      // q[3] quad, kp=1
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc134d          // FMLA V13.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b0d          // FMLA V13.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd136d          // FMLA V13.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b2d          // FMLA V13.2D, V25.2D, V29.D[1]   d3
	VLD1 (R19), [V28.S4]      // q[4] quad, kp=1
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc1351          // FMLA V17.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b11          // FMLA V17.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd1371          // FMLA V17.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b31          // FMLA V17.2D, V25.2D, V29.D[1]   d3
	VLD1 (R20), [V28.S4]      // q[5] quad, kp=1
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc1355          // FMLA V21.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b15          // FMLA V21.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd1375          // FMLA V21.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b35          // FMLA V21.2D, V25.2D, V29.D[1]   d3

	// key-pair 2: keys 4,5
	VLD1.P 16(R9), [V24.S4]
	VLD1.P 16(R10), [V25.S4]
	WORD $0x4e993b1a          // ZIP1 V26.4S, V24.4S, V25.4S
	WORD $0x4e997b1b          // ZIP2 V27.4S, V24.4S, V25.4S
	WORD $0x4e617b58          // FCVTL2 V24.2D, V26.4S   d1 pair (reuse dead raw-A)
	WORD $0x0e617b5a          // FCVTL  V26.2D, V26.2S   d0 pair (in place)
	WORD $0x4e617b79          // FCVTL2 V25.2D, V27.4S   d3 pair (reuse dead raw-B)
	WORD $0x0e617b7b          // FCVTL  V27.2D, V27.2S   d2 pair (in place)
	VLD1 (R14), [V28.S4]      // q[0] quad, kp=2
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc1342          // FMLA V2.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b02          // FMLA V2.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd1362          // FMLA V2.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b22          // FMLA V2.2D, V25.2D, V29.D[1]   d3
	VLD1 (R15), [V28.S4]      // q[1] quad, kp=2
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc1346          // FMLA V6.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b06          // FMLA V6.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd1366          // FMLA V6.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b26          // FMLA V6.2D, V25.2D, V29.D[1]   d3
	VLD1 (R16), [V28.S4]      // q[2] quad, kp=2
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc134a          // FMLA V10.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b0a          // FMLA V10.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd136a          // FMLA V10.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b2a          // FMLA V10.2D, V25.2D, V29.D[1]   d3
	VLD1 (R17), [V28.S4]      // q[3] quad, kp=2
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc134e          // FMLA V14.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b0e          // FMLA V14.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd136e          // FMLA V14.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b2e          // FMLA V14.2D, V25.2D, V29.D[1]   d3
	VLD1 (R19), [V28.S4]      // q[4] quad, kp=2
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc1352          // FMLA V18.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b12          // FMLA V18.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd1372          // FMLA V18.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b32          // FMLA V18.2D, V25.2D, V29.D[1]   d3
	VLD1 (R20), [V28.S4]      // q[5] quad, kp=2
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc1356          // FMLA V22.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b16          // FMLA V22.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd1376          // FMLA V22.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b36          // FMLA V22.2D, V25.2D, V29.D[1]   d3

	// key-pair 3: keys 6,7
	VLD1.P 16(R11), [V24.S4]
	VLD1.P 16(R12), [V25.S4]
	WORD $0x4e993b1a          // ZIP1 V26.4S, V24.4S, V25.4S
	WORD $0x4e997b1b          // ZIP2 V27.4S, V24.4S, V25.4S
	WORD $0x4e617b58          // FCVTL2 V24.2D, V26.4S   d1 pair (reuse dead raw-A)
	WORD $0x0e617b5a          // FCVTL  V26.2D, V26.2S   d0 pair (in place)
	WORD $0x4e617b79          // FCVTL2 V25.2D, V27.4S   d3 pair (reuse dead raw-B)
	WORD $0x0e617b7b          // FCVTL  V27.2D, V27.2S   d2 pair (in place)
	VLD1 (R14), [V28.S4]      // q[0] quad, kp=3
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc1343          // FMLA V3.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b03          // FMLA V3.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd1363          // FMLA V3.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b23          // FMLA V3.2D, V25.2D, V29.D[1]   d3
	VLD1 (R15), [V28.S4]      // q[1] quad, kp=3
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc1347          // FMLA V7.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b07          // FMLA V7.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd1367          // FMLA V7.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b27          // FMLA V7.2D, V25.2D, V29.D[1]   d3
	VLD1 (R16), [V28.S4]      // q[2] quad, kp=3
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc134b          // FMLA V11.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b0b          // FMLA V11.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd136b          // FMLA V11.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b2b          // FMLA V11.2D, V25.2D, V29.D[1]   d3
	VLD1 (R17), [V28.S4]      // q[3] quad, kp=3
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc134f          // FMLA V15.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b0f          // FMLA V15.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd136f          // FMLA V15.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b2f          // FMLA V15.2D, V25.2D, V29.D[1]   d3
	VLD1 (R19), [V28.S4]      // q[4] quad, kp=3
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc1353          // FMLA V19.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b13          // FMLA V19.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd1373          // FMLA V19.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b33          // FMLA V19.2D, V25.2D, V29.D[1]   d3
	VLD1 (R20), [V28.S4]      // q[5] quad, kp=3
	WORD $0x4e617b9d          // FCVTL2 V29.2D, V28.4S   [q_d2,q_d3]
	WORD $0x0e617b9c          // FCVTL  V28.2D, V28.2S   [q_d0,q_d1] (in place)
	WORD $0x4fdc1357          // FMLA V23.2D, V26.2D, V28.D[0]   d0
	WORD $0x4fdc1b17          // FMLA V23.2D, V24.2D, V28.D[1]   d1
	WORD $0x4fdd1377          // FMLA V23.2D, V27.2D, V29.D[0]   d2
	WORD $0x4fdd1b37          // FMLA V23.2D, V25.2D, V29.D[1]   d3

	// advance q pointers by 16 bytes (next d-quad), K pointers already .P-advanced
	ADD  $16, R14, R14
	ADD  $16, R15, R15
	ADD  $16, R16, R16
	ADD  $16, R17, R17
	ADD  $16, R19, R19
	ADD  $16, R20, R20

	SUBS $1, R24, R24
	BNE  qkg6quad

	// store: for each g, narrow 4 key-pair accumulators (8 keys) to f32 and store.
	// R26 = this block's query-g row base (starts at R22, advances by dstRowStrideBytes);
	// R22 itself is left untouched so it still names this block's query-0 column offset.
	MOVD R22, R26
	WORD $0x0e616818          // FCVTN  V24.2S, V0.2D   keys 0,1 -> f32
	WORD $0x4e616838          // FCVTN2 V24.4S, V1.2D   keys 2,3
	WORD $0x0e616859          // FCVTN  V25.2S, V2.2D   keys 4,5 -> f32
	WORD $0x4e616879          // FCVTN2 V25.4S, V3.2D   keys 6,7
	MOVD R26, R25                  // g=0 store cursor
	VST1.P [V24.S4], 16(R25)
	VST1   [V25.S4], (R25)
	ADD  R23, R26, R26             // next query row base

	WORD $0x0e616898          // FCVTN  V24.2S, V4.2D   keys 0,1 -> f32
	WORD $0x4e6168b8          // FCVTN2 V24.4S, V5.2D   keys 2,3
	WORD $0x0e6168d9          // FCVTN  V25.2S, V6.2D   keys 4,5 -> f32
	WORD $0x4e6168f9          // FCVTN2 V25.4S, V7.2D   keys 6,7
	MOVD R26, R25                  // g=1 store cursor
	VST1.P [V24.S4], 16(R25)
	VST1   [V25.S4], (R25)
	ADD  R23, R26, R26             // next query row base

	WORD $0x0e616918          // FCVTN  V24.2S, V8.2D   keys 0,1 -> f32
	WORD $0x4e616938          // FCVTN2 V24.4S, V9.2D   keys 2,3
	WORD $0x0e616959          // FCVTN  V25.2S, V10.2D   keys 4,5 -> f32
	WORD $0x4e616979          // FCVTN2 V25.4S, V11.2D   keys 6,7
	MOVD R26, R25                  // g=2 store cursor
	VST1.P [V24.S4], 16(R25)
	VST1   [V25.S4], (R25)
	ADD  R23, R26, R26             // next query row base

	WORD $0x0e616998          // FCVTN  V24.2S, V12.2D   keys 0,1 -> f32
	WORD $0x4e6169b8          // FCVTN2 V24.4S, V13.2D   keys 2,3
	WORD $0x0e6169d9          // FCVTN  V25.2S, V14.2D   keys 4,5 -> f32
	WORD $0x4e6169f9          // FCVTN2 V25.4S, V15.2D   keys 6,7
	MOVD R26, R25                  // g=3 store cursor
	VST1.P [V24.S4], 16(R25)
	VST1   [V25.S4], (R25)
	ADD  R23, R26, R26             // next query row base

	WORD $0x0e616a18          // FCVTN  V24.2S, V16.2D   keys 0,1 -> f32
	WORD $0x4e616a38          // FCVTN2 V24.4S, V17.2D   keys 2,3
	WORD $0x0e616a59          // FCVTN  V25.2S, V18.2D   keys 4,5 -> f32
	WORD $0x4e616a79          // FCVTN2 V25.4S, V19.2D   keys 6,7
	MOVD R26, R25                  // g=4 store cursor
	VST1.P [V24.S4], 16(R25)
	VST1   [V25.S4], (R25)
	ADD  R23, R26, R26             // next query row base

	WORD $0x0e616a98          // FCVTN  V24.2S, V20.2D   keys 0,1 -> f32
	WORD $0x4e616ab8          // FCVTN2 V24.4S, V21.2D   keys 2,3
	WORD $0x0e616ad9          // FCVTN  V25.2S, V22.2D   keys 4,5 -> f32
	WORD $0x4e616af9          // FCVTN2 V25.4S, V23.2D   keys 6,7
	MOVD R26, R25                  // g=5 store cursor
	VST1.P [V24.S4], 16(R25)
	VST1   [V25.S4], (R25)

	// advance to next block: R22 (query-0 column offset) += 32 bytes; K rows base += rowStride*8
	ADD  $32, R22, R22
	ADD  R3<<3, R2, R2
	SUBS $1, R21, R21
	BNE  qkg6block
	RET
